version: 2.1

jobs:
  build:
    docker:
      - image: shiftleft/sast-scan
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Perform ShiftLeft Scan
          command: |
            scan --build
      - store_artifacts:
          path: reports
          destination: sast-scan-reports
